version: '3.7'
 
services:
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
   - PMA_HOST=mysql
#  restart: always
  ports:
   - 9090:80
   
 mysql:
  image: mysql:5.6
  container_name: mysql
#  restart: always
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
   
 itop:
  build: .
  container_name: itop
#  restart: always
  ports:
   - 8080:80
